Update genai notebooks - Cameron J.
STRIDES/NIHCloudLabAzure pull request #94
Opened 2024-12-05 19:53 UTC by cjackson202

## Pull Request Template

### Description

*Provide a description of your changes here. If this PR is related to an issue, list the issue number/name here*

### Assignee

*Assignees: @kyleoconnell-NIH*

## PR checklist
*Please ensure the following:*
- [ ] This comment contains a description of changes (with reason).
- [ ] All changes were tested.
- [ ] If you've fixed a bug mention the issue number/name.
- [ ] Apply approriate tags (e.g. documentation, bug)

2024-12-17 15:13 UTC, zbyosufzai requested changes
please address the comments I've left and let me know if you have any questions!

2024-12-17 15:13 UTC, zbyosufzai commented on notebooks/GenAI/embedding_demos/readme.md
> +The Azure OpenAI Demo w/ Streamlit Frontend is designed to host various demonstrations that showcase the capabilities of Azure OpenAI with a Streamlit frontend. Demonstrations include utilizing Azure
in this overview can you also indicate the python script does like Dome_suite launches your streamlit UI. Where do these scripts come in AI_Search_Query.py and AOAI_Embeddings.py? This README might also require a tutorial just to help break doen how streamlit works and how all of these scripts are connected.

2024-12-17 16:17 UTC, zbyosufzai commented on notebooks/GenAI/notebooks/AISearch_RAG_chatbot.ipynb
> +    "from azure.identity import DefaultAzureCredential  \n",
ran into an error with importing this python package: `ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/azure/core/credentials.py)`

2024-12-17 16:21 UTC, zbyosufzai commented on notebooks/GenAI/notebooks/AISearch_RAG_chatbot.ipynb
> +    "from openai import AzureOpenAI  \n",
another import error: `ImportError: cannot import name 'Sequence' from 'typing_extensions' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/typing_extensions.py)`

2024-12-17 17:22 UTC, zbyosufzai commented on notebooks/GenAI/example_scripts/workshop_embedding.py
> +df.to_csv('.\\microsoft-earnings_embeddings.csv', index=False)
typo please change `.\\` to `../`

2024-12-17 17:22 UTC, zbyosufzai commented on notebooks/GenAI/example_scripts/workshop_search.py
> +df = pd.read_csv('.\\microsoft-earnings_embeddings.csv')
typo please change `.\\` to `../`

2024-12-17 17:22 UTC, zbyosufzai commented on notebooks/GenAI/example_scripts/workshop_search.py
> +df = pd.read_csv('.\\microsoft-earnings_embeddings.csv')
these two example scripts my require a README to explain they are connected

2024-12-17 17:22 UTC, zbyosufzai commented on notebooks/GenAI/azure_infra_setup/README.md
> +Deploy the [ARM template](/notebooks/GenAI/azure_infra_setup/arm_resources.json) to create the Azure Storage Account, Azure AI Search, and Azure OpenAI resources.
link didn't work please change to `arm_resources.json`

2025-01-07 13:45 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +Welcome! This guide will help you set up your Azure environment to complete the activities in the [Azure GenAI](../) directory of the NIH Cloud Lab. We will walk you through the steps required to con
Added note to Prerequisites, advising the user of such circumstance. If using such environment, user is encouraged to skip step 1 and move directly to step 2.

2025-01-07 14:06 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +- PowerShell installed on your machine (option 1)
Choosing between Azure CLI and PowerShell comes down to personal preference and the working environment. Brief overview added to the Prerequisites section for helping users choose.

2025-01-07 15:09 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +# Setting Up Azure Environment for Azure GenAI Cloud Lab
Executing the ARM template in this README does not incur any cost. However, the resources deployed in the ARM template will incur costs overtime, based on Azure's pricing for each resource. These resources are the same resources that were originally being used in the Cloud Lab around AOAI, such as AI Search, Blob Storage, and Azure OpenAI service. The ARM template serves as an automated way to deploy these resources to a resource group, rather than having to manually deploy each resource from the Azure portal. "## Resources and Cost Breakdown" added to readme with estimated costs from Azure Pricing Calculator based on SKUs found in the ARM template for each resource.

2025-01-07 16:42 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +Welcome! This guide will help you set up your Azure environment to complete the activities in the [Azure GenAI](../) directory of the NIH Cloud Lab. We will walk you through the steps required to con
Overview of what an ARM template is has been added to the "## Resources and Cost Breakdown" section of README.

2025-01-07 16:45 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +searchServiceKey = az search admin-key show --resource-group resourceGroupName --service-name $searchServiceName --query primaryKey -o tsv
Basic pricing tier used for Azure AI Search deployment with this command. The tier is identified in the ARM template logic as basic sku. The tier has also been added to the "## Resources and Cost Breakdown" section along with cost.

2025-01-07 21:12 UTC, cjackson202 commented on notebooks/GenAI/notebooks/AISearch_RAG_chatbot.ipynb
Tutorial has been updated following the tutorial checklist. Remaining questions:
- Where should skill level identification be placed in the tutorial structure?
- With pricing for most services being consumption based, cost per usage has been identified with each resource in the Prerequisites section.

2025-01-08 17:34 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +Retrieve the API keys for each service created by the ARM template deployment. These secrets are confidential and should be handled appropriately. Once the output is received, the values will be adde
Description added to this section of the ReadMe, explaining what .gitignore does and why it is important that the .env file has been added.

2025-01-08 17:58 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +# Setting Up Azure Environment for Azure GenAI Cloud Lab
Tutorial has been structured to follow the outline laid out in checklist. Skill level identification has not yet been added. Where should skill level identification be placed in the tutorial structure?

2025-01-08 17:59 UTC, cjackson202 commented on notebooks/GenAI/embedding_demos/readme.md
> +        cd .\notebooks\GenAI
Backslashes have been changed to forward slashes.

2025-01-08 18:02 UTC, cjackson202 commented on notebooks/GenAI/embedding_demos/readme.md
> +    cd .\notebooks\GenAI\embedding_demos
Corrections have been made to directory path and slashes.

2025-01-08 18:56 UTC, cjackson202 commented on notebooks/GenAI/notebooks/AISearch_RAG_chatbot.ipynb
> +    "from azure.identity import DefaultAzureCredential  \n",
Were you able to successfully execute the pip command in cell one to install packages in the kernel? If so, it's possible there can be a discrepancy between the Python version you are using and the Python version which the code was built on top of. The notebook is using Python 3.11.9. Please confirm if you are using a separate version from this.

2025-01-08 19:36 UTC, cjackson202 commented on notebooks/GenAI/example_scripts/workshop_search.py
> +df = pd.read_csv('.\\microsoft-earnings_embeddings.csv')
os.path.join has been incorporated to ensure the input file "'microsoft-earnings_embeddings.csv" can be read into the df across different operating systems, including Azure ML environment. I agree a README will enhance the awareness that the two scripts are connected. Proposing that we create a README for the /example_scripts directory, encompassing all scripts in this directory and identifying what each script does and any connections they may have.

2025-01-08 19:38 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +Deploy the [ARM template](/notebooks/GenAI/azure_infra_setup/arm_resources.json) to create the Azure Storage Account, Azure AI Search, and Azure OpenAI resources.
Adjustment made to arm_resources.json.

2025-01-10 13:44 UTC, cjackson202 commented on notebooks/GenAI/embedding_demos/Demo_Suite.py
> +import streamlit as st
Streamlit expects to run the demo application locally on port 8501, explaining the Streamlit site will not launch when running the demo from Azure ML. A workaround involves utilizing Ngrok, which provides a secure tunnel for the Streamlit demo app, exposing the application to the internet. This is a secure and efficient alternative to accessing the Streamlit app without needing to run locally from port 8501.

2025-01-10 13:45 UTC, cjackson202 commented on notebooks/GenAI/embedding_demos/Demo_Suite.py
> +import streamlit as st
Ngrock script has been created and successfully tested with the Streamlit demo in my Azure ML env. Demo now works as expected. Documentation added to readme, section "## Executing the Azure OpenAI Demo w/ Streamlit Frontend" on what this script does and how to execute.

2025-01-10 14:30 UTC, cjackson202 commented on notebooks/GenAI/azure_infra_setup/README.md
> +Welcome! This guide will help you set up your Azure environment to complete the activities in the [Azure GenAI](../) directory of the NIH Cloud Lab. We will walk you through the steps required to con
Proposing we also incorporate steps to deploying Azure Resources manually from the Azure portal in this tutorial as well. Therefore, we can have a unified landing zone for users to configure their working environments for all tutorials in GenAI notebook using either the ARM file as an option or manual deployments as an option. In each tutorial for prerequisites we can then link users to this landing zone if they have not yet configured the environment and resources.

2025-04-23 23:56 UTC, zbyosufzai commented on notebooks/GenAI/embedding_demos/Demo_Suite.py
> +import streamlit as st
removed Ngrok found an alternative method

2025-04-23 23:56 UTC, zbyosufzai approved these changes

2025-04-24 00:02 UTC, merged